language: ruby
rvm: 2.3.3
cache:
  bundler: true
  directories:
  - node_modules
branches:
  only:
  - master
before_install:
- nvm install 7.4.0
install:
- npm install
- bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}
script:
- bundle exec middleman build
after_success:
- cd build
- cp ../.config/now.json .
- npm install -g now --unsafe-perm
- now --token "$NOW_TOKEN"
- now alias --token "$NOW_TOKEN"
env:
  global:
    secure: YMIR5kKc0VLNtKGkvLW/vaJqDyE4kaRjic64Wz5nf7oja/X5oR6GTFsV1qVUYrL/V2aQPLoxBAyjexCQpAl/MO6JwCoGMi5rH61hPk574jIwJ+rYdbE28Y+zqh1VJ63oUJbriavVPg5+WIXp3CImPDwhfvQKq8GGCagMFsHJ1+MX88nJYQ6jRJJMsy1jCdb5riLAoCSs0PeHQusj1zeVVLEesp17Os7U3yGsr4odoykGdjVXul8mnNwuHdo9Og6J4wcRmdXtbMzeLGApMzIa7E+7RDlQeROqsfT+XDvb9WP4K22y2U5Tc+j80we/6SRaQzCBuMI4l9NWUdVVXo6XY98ZJKSaxQ8gbGEV/eGecGhGRg+oHT9Brdf/Tk93m2+/1R6irMPt1EkDxvnk8PZBpLgdXkjVt1Edd1X0rig+Zcme/gTanLBM7Wfg3kzx1WV/VxXrvSP1CYOx2aQIYLq7p9XPZwH/OIaV6EHhnAnKs79cYfd31fe5fwH9MaOtgDtIWAFs+m1gOkS8NmEAhuOlMQlHSirOKNEch4K9G2IpENJCcbbw18LvESRmNoQ/qQrWYkw7+s7oy24hnQyhvIdRbr/r4cQcfKMv1SHKrWCssWyGakr5+tbrD7tEEFNC3QT6dJ/Jv4popDFwzJdJNCl5NOKsCXla+0BJcS8zlvTY9f0=
