language: ruby
rvm: 2.3.3
cache:
  bundler: true
  directories:
  - node_modules
branches:
  only:
  - master
before_install:
- nvm install 7.4.0
install:
- npm install
- bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}
before_script:
- git config --global user.name "hnbot"
- git config --global user.email "nygrenh+hnbot@gmail.com"
- export COMMIT_MESSAGE=Update:\ $(git log -1 --pretty=%s)
- git clone -b gh-pages --single-branch https://github.com/materiaalit/ohjelmointi-18.git
  build
script:
- bundle exec middleman build
after_success:
- cd build
- git checkout HEAD README.md .github
- git add --all
- git commit -m "$COMMIT_MESSAGE"
- git push "https://hnbot:$GITHUB_API_KEY@github.com/materiaalit/ohjelmointi-18.git"
  gh-pages:gh-pages 2>&1 | sed "s/$GITHUB_API_KEY/<confidential>/g"
env:
  global:
    secure: Xw2pWgrIA7FXKkT9vYJromsdISQASMniPrqIZvToHWh+MdA30sdyFFvpltIWqvrvCg44M9yd7im33+ciE4BRkvXk57epaYeiE0L3KAqY/QxfZMIyxoo3t9TMydHg5EIBh2WXe3we4c/KU3En2WayP2hdArwm/pBvP2g7mhbuntkVRCWhoicOaEBSVDNXDU46a5qhNGyPaCwzDqlLZs/BnymZIUK+07O+ZAufV/Q66z3ldhnXNkrDZfx/TTYawn5cW1h1sguXeyJ4i1rTb6PwAQOCcSfY5xe+plpFQImTahISuo3wrkBA8qIvlymWpMNY6mypH0gA2mycs/bSg659O7JRQLIvIuvxkBMnpMxH2DZ++CZr7nDiOR6eTEj/Yz2k+cVOghAFEtAKpx2YWia16vw0j5DX2c8tfVXOOY6baSMV16SGFVR40Riil1uf9D1mSk3QE3WF7OEDj9rZfiNROaoPbN4JjJQCeUPxC5IR77hB0ONraWMu8wz24yJ6TMg7VSdY5dPWFQQSQhPOc3cmK7S7O1BvQV6uio0fWHLAJ2Xd2twtXscpFfNiWx7DJWlf+Kj5uoPrbc7oZKRd+vQAxnpWho/3606hFBjCEoCQa74VUCCYNUQLOdeIV79OihfqBkuW6IvpfABhqOF+ElsA2SxkzB1PzA1NZj41BzyYSLk=
